server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://3.110.58.94:30480/loki/api/v1/push

scrape_configs:
  - job_name: jenkins-journal

    journal:
      max_age: 12h
      labels:
        job: jenkins
        instance: jenkins-ec2

    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: unit

---- need to keep this file in sudo vi /etc/promtail-config.yaml path------
