apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-manual
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod

      - job_name: "sonarqube"
        metrics_path: /api/monitoring/metrics
        static_configs:
          - targets: ["sonarqube-service.sonarqube.svc.cluster.local:9000"]
        basic_auth:
          username: sqa_aff0e3d92478e0296e0be4d0e8f8ebb7d8e28e5b
          password: ""

      - job_name: "kubernetes-cadvisor"
        kubernetes_sd_configs:
          - role: node

        scheme: https
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        tls_config:
          insecure_skip_verify: true

        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443

          - source_labels: [__meta_kubernetes_node_name]
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

